// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: dapr/proto/components/v1/binding.proto

package components

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InputBindingClient is the client API for InputBinding service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InputBindingClient interface {
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Read(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReadResponse, error)
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type inputBindingClient struct {
	cc grpc.ClientConnInterface
}

func NewInputBindingClient(cc grpc.ClientConnInterface) InputBindingClient {
	return &inputBindingClient{cc}
}

func (c *inputBindingClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/dapr.proto.components.v1.InputBinding/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inputBindingClient) Read(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.components.v1.InputBinding/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inputBindingClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/dapr.proto.components.v1.InputBinding/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InputBindingServer is the server API for InputBinding service.
// All implementations should embed UnimplementedInputBindingServer
// for forward compatibility
type InputBindingServer interface {
	Init(context.Context, *InitRequest) (*emptypb.Empty, error)
	Read(context.Context, *emptypb.Empty) (*ReadResponse, error)
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
}

// UnimplementedInputBindingServer should be embedded to have forward compatible implementations.
type UnimplementedInputBindingServer struct {
}

func (UnimplementedInputBindingServer) Init(context.Context, *InitRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedInputBindingServer) Read(context.Context, *emptypb.Empty) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedInputBindingServer) Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

// UnsafeInputBindingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InputBindingServer will
// result in compilation errors.
type UnsafeInputBindingServer interface {
	mustEmbedUnimplementedInputBindingServer()
}

func RegisterInputBindingServer(s grpc.ServiceRegistrar, srv InputBindingServer) {
	s.RegisterService(&InputBinding_ServiceDesc, srv)
}

func _InputBinding_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InputBindingServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.components.v1.InputBinding/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InputBindingServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InputBinding_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InputBindingServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.components.v1.InputBinding/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InputBindingServer).Read(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InputBinding_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InputBindingServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.components.v1.InputBinding/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InputBindingServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// InputBinding_ServiceDesc is the grpc.ServiceDesc for InputBinding service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InputBinding_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapr.proto.components.v1.InputBinding",
	HandlerType: (*InputBindingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _InputBinding_Init_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _InputBinding_Read_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _InputBinding_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dapr/proto/components/v1/binding.proto",
}

// OutputBindingClient is the client API for OutputBinding service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OutputBindingClient interface {
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type outputBindingClient struct {
	cc grpc.ClientConnInterface
}

func NewOutputBindingClient(cc grpc.ClientConnInterface) OutputBindingClient {
	return &outputBindingClient{cc}
}

func (c *outputBindingClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/dapr.proto.components.v1.OutputBinding/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outputBindingClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.components.v1.OutputBinding/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outputBindingClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/dapr.proto.components.v1.OutputBinding/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutputBindingServer is the server API for OutputBinding service.
// All implementations should embed UnimplementedOutputBindingServer
// for forward compatibility
type OutputBindingServer interface {
	Init(context.Context, *InitRequest) (*emptypb.Empty, error)
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
}

// UnimplementedOutputBindingServer should be embedded to have forward compatible implementations.
type UnimplementedOutputBindingServer struct {
}

func (UnimplementedOutputBindingServer) Init(context.Context, *InitRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedOutputBindingServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedOutputBindingServer) Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

// UnsafeOutputBindingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutputBindingServer will
// result in compilation errors.
type UnsafeOutputBindingServer interface {
	mustEmbedUnimplementedOutputBindingServer()
}

func RegisterOutputBindingServer(s grpc.ServiceRegistrar, srv OutputBindingServer) {
	s.RegisterService(&OutputBinding_ServiceDesc, srv)
}

func _OutputBinding_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutputBindingServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.components.v1.OutputBinding/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutputBindingServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutputBinding_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutputBindingServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.components.v1.OutputBinding/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutputBindingServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutputBinding_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutputBindingServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.components.v1.OutputBinding/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutputBindingServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// OutputBinding_ServiceDesc is the grpc.ServiceDesc for OutputBinding service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OutputBinding_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapr.proto.components.v1.OutputBinding",
	HandlerType: (*OutputBindingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _OutputBinding_Init_Handler,
		},
		{
			MethodName: "Invoke",
			Handler:    _OutputBinding_Invoke_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _OutputBinding_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dapr/proto/components/v1/binding.proto",
}
