// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: dapr/proto/components/v1/middleware.proto

package components

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HttpMiddlewareClient is the client API for HttpMiddleware service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HttpMiddlewareClient interface {
	Init(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*HandlerResponse, error)
	HandleHeader(ctx context.Context, in *HttpRequestHeader, opts ...grpc.CallOption) (*HeaderHandlerResponse, error)
	HandleBody(ctx context.Context, in *HttpRequestBody, opts ...grpc.CallOption) (*BodyHandlerResponse, error)
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type httpMiddlewareClient struct {
	cc grpc.ClientConnInterface
}

func NewHttpMiddlewareClient(cc grpc.ClientConnInterface) HttpMiddlewareClient {
	return &httpMiddlewareClient{cc}
}

func (c *httpMiddlewareClient) Init(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*HandlerResponse, error) {
	out := new(HandlerResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.components.v1.HttpMiddleware/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpMiddlewareClient) HandleHeader(ctx context.Context, in *HttpRequestHeader, opts ...grpc.CallOption) (*HeaderHandlerResponse, error) {
	out := new(HeaderHandlerResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.components.v1.HttpMiddleware/HandleHeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpMiddlewareClient) HandleBody(ctx context.Context, in *HttpRequestBody, opts ...grpc.CallOption) (*BodyHandlerResponse, error) {
	out := new(BodyHandlerResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.components.v1.HttpMiddleware/HandleBody", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpMiddlewareClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/dapr.proto.components.v1.HttpMiddleware/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HttpMiddlewareServer is the server API for HttpMiddleware service.
// All implementations should embed UnimplementedHttpMiddlewareServer
// for forward compatibility
type HttpMiddlewareServer interface {
	Init(context.Context, *MetadataRequest) (*HandlerResponse, error)
	HandleHeader(context.Context, *HttpRequestHeader) (*HeaderHandlerResponse, error)
	HandleBody(context.Context, *HttpRequestBody) (*BodyHandlerResponse, error)
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
}

// UnimplementedHttpMiddlewareServer should be embedded to have forward compatible implementations.
type UnimplementedHttpMiddlewareServer struct {
}

func (UnimplementedHttpMiddlewareServer) Init(context.Context, *MetadataRequest) (*HandlerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedHttpMiddlewareServer) HandleHeader(context.Context, *HttpRequestHeader) (*HeaderHandlerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleHeader not implemented")
}
func (UnimplementedHttpMiddlewareServer) HandleBody(context.Context, *HttpRequestBody) (*BodyHandlerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleBody not implemented")
}
func (UnimplementedHttpMiddlewareServer) Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

// UnsafeHttpMiddlewareServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HttpMiddlewareServer will
// result in compilation errors.
type UnsafeHttpMiddlewareServer interface {
	mustEmbedUnimplementedHttpMiddlewareServer()
}

func RegisterHttpMiddlewareServer(s grpc.ServiceRegistrar, srv HttpMiddlewareServer) {
	s.RegisterService(&HttpMiddleware_ServiceDesc, srv)
}

func _HttpMiddleware_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpMiddlewareServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.components.v1.HttpMiddleware/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpMiddlewareServer).Init(ctx, req.(*MetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpMiddleware_HandleHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpRequestHeader)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpMiddlewareServer).HandleHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.components.v1.HttpMiddleware/HandleHeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpMiddlewareServer).HandleHeader(ctx, req.(*HttpRequestHeader))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpMiddleware_HandleBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpRequestBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpMiddlewareServer).HandleBody(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.components.v1.HttpMiddleware/HandleBody",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpMiddlewareServer).HandleBody(ctx, req.(*HttpRequestBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpMiddleware_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpMiddlewareServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.components.v1.HttpMiddleware/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpMiddlewareServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// HttpMiddleware_ServiceDesc is the grpc.ServiceDesc for HttpMiddleware service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HttpMiddleware_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dapr.proto.components.v1.HttpMiddleware",
	HandlerType: (*HttpMiddlewareServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _HttpMiddleware_Init_Handler,
		},
		{
			MethodName: "HandleHeader",
			Handler:    _HttpMiddleware_HandleHeader_Handler,
		},
		{
			MethodName: "HandleBody",
			Handler:    _HttpMiddleware_HandleBody_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _HttpMiddleware_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dapr/proto/components/v1/middleware.proto",
}
